apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  labels:
    app: keycloak
type: Opaque
data:
  KEYCLOAK_PASSWORD: #yourkey
  DB_PASSWORD: #enter your db encryopted key
stringData:
  KEYCLOAK_PASSWORD: #enter password as string
  DB_PASSWORD: #enter password as string
