apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-store-config
  namespace: monitoring
data:
  thanos-store.yml: |-
    type: S3
    config:
      bucket: bucketname
      endpoint: "s3.zonename.amazonaws.com"
      access_key: ""
      secret_key: ""
      insecure: false
      signature_version2: false
      encrypt_sse: true
      http_config:
          idle_conn_timeout: 90s

